### ISSUE TITLE
Emulate controller?

### ISSUE THREAD

**Issue by Thequietcroc** [StrikerX3/JXInput#14]
Is it possible to use this to emulate pressing an XInput button and such instead of reacting to it?

**Comment by StrikerX3** [comment]
Do you mean to generate button presses so that other applications could capture them (similar to [`java.awt.Robot`](https://docs.oracle.com/javase/8/docs/api/java/awt/Robot.html))? That is not the goal of JXInput; it's meant to be an XInput wrapper, so it can only do [whatever XInput allows](https://msdn.microsoft.com/en-us/library/windows/desktop/hh405053(v=vs.85).aspx). It's not a controller emulator, and will never be.

If you are trying to emulate button presses within your application with the purposes of testing, you could simply override the values of the desired public fields from [`XInputButtons`](https://github.com/StrikerX3/JXInput/blob/master/XInputDevice_Java/src/main/java/com/ivan/xinput/XInputButtons.java) or [`XInputAxes`](https://github.com/StrikerX3/JXInput/blob/master/XInputDevice_Java/src/main/java/com/ivan/xinput/XInputAxes.java) right after polling, like this:
```java
XInputDevice device = ...;
device.poll();
// override values for testing purposes
XInputButtons buttons = device.getComponents().getButtons();
buttons.a = true;
buttons.x = true;
```
